package shiper

import "github.com/shiper-app/shiper-go/internal/genapi"

type RequestEditorFn = genapi.RequestEditorFn
type HttpRequestDoer = genapi.HttpRequestDoer

type ProjectListParams = genapi.ProjectListParams
type ProjectCreateRequest = genapi.ProjectCreateJSONRequestBody
type ProjectUpdateRequest = genapi.ProjectUpdateJSONRequestBody
type ProjectEnvironmentUpdateRequest = genapi.ProjectEnvironmentsUpdateJSONRequestBody
type ProjectEnvironmentDeploymentsListParams = genapi.ProjectEnvironmentsDeploymentsListParams
type ProjectEnvironmentDeploymentsPatchRequest = genapi.ProjectEnvironmentsDeploymentsPatchJSONRequestBody
type ProjectEnvironmentDeploymentsPatchResponse = genapi.ProjectEnvironmentsDeploymentsPatchResponse
type ProjectEnvironmentDeploymentRedeployRequest = genapi.ProjectEnvironmentsDeploymentsRedeployJSONRequestBody
type ProjectEnvironmentDomainAddRequest = genapi.ProjectEnvironmentsDomainsAddJSONRequestBody
type UserSearchParams = genapi.UserSearchParams
type VariablesListParams = genapi.ProjectVariablesListParams
type VariablesDeleteRequest = genapi.ProjectVariablesDeleteJSONRequestBody
type VariablesUpsertRequest = genapi.ProjectVariablesUpsertJSONRequestBody

type ProjectListResponse = genapi.ProjectListResponse
type ProjectGetResponse = genapi.ProjectGetResponse
type ProjectCreateResponse = genapi.ProjectCreateResponse
type ProjectUpdateResponse = genapi.ProjectUpdateResponse
type ProjectDeleteResponse = genapi.ProjectDeleteResponse
type ProjectEnvironmentsListResponse = genapi.ProjectEnvironmentsListResponse
type ProjectEnvironmentsUpdateResponse = genapi.ProjectEnvironmentsUpdateResponse
type ProjectEnvironmentsDeploymentsListResponse = genapi.ProjectEnvironmentsDeploymentsListResponse
type ProjectEnvironmentsDeploymentsCancelResponse = genapi.ProjectEnvironmentsDeploymentsCancelResponse
type ProjectEnvironmentsDeploymentsRedeployResponse = genapi.ProjectEnvironmentsDeploymentsRedeployResponse
type ProjectEnvironmentsDomainsListResponse = genapi.ProjectEnvironmentsDomainsListResponse
type ProjectEnvironmentsDomainsAddResponse = genapi.ProjectEnvironmentsDomainsAddResponse
type ProjectEnvironmentsDomainsDeleteResponse = genapi.ProjectEnvironmentsDomainsDeleteResponse
type ProjectEnvironmentsDomainsValidateDNSResponse = genapi.ProjectEnvironmentsDomainsValidateDnsResponse

type UserMeResponse = genapi.UserMeResponse
type UserGetResponse = genapi.UserGetResponse
type UserSearchResponse = genapi.UserSearchResponse

type VariablesListResponse = genapi.ProjectVariablesListResponse
type VariablesUpsertResponse = genapi.ProjectVariablesUpsertResponse
type VariablesDeleteResponse = genapi.ProjectVariablesDeleteResponse
